Added spanish translation
Nain57/Smart-AutoClicker pull request #321
Opened 2023-10-01 16:54 UTC by MxtAppz

# 📝 Description of the pull request, what, why and where

This PR has added the Spanish translation

## ✅ How to test

-Set the language to Spanish

## 📹 Demo

2023-10-01 17:16 UTC, Nain57 commented
Hi and thanks for your contribution.

Quick review: 
* You don't need to recreate files that does not contains a string to be translated (colors.xml, dimens.xml ...). Basically, you should only have a strings.xml file in the values-es folders (beside some exceptions like event_default_config)
* Be carefull with the indentation, it seems wrong in some strings.xml files

I will look more in details this week if i can find some time, but you can already fix those issues.

2023-10-01 17:18 UTC, Nain57 requested changes
Hi and thanks for your contribution.

Quick review:

* You don't need to recreate files that does not contains a string to be translated (colors.xml, dimens.xml ...). Basically, you should only have a strings.xml file in the values-es folders (beside some exceptions like event_default_config)
* Be carefull with the indentation, it seems wrong in some strings.xml files

I will look more in details this week if i can find some time, but you can already fix those issues.
Thank you again !

2023-10-01 17:20 UTC, c-sanchez commented
😮 Coincidentally I'm finishing my translation in Spanish, I just needed to translate the last tutorial 😅

2023-10-01 17:57 UTC, MxtAppz commented
> Hi and thanks for your contribution.
> 
> Quick review:
> 
>     * You don't need to recreate files that does not contains a string to be translated (colors.xml, dimens.xml ...). Basically, you should only have a strings.xml file in the values-es folders (beside some exceptions like event_default_config)
> 
>     * Be carefull with the indentation, it seems wrong in some strings.xml files
> 
> 
> I will look more in details this week if i can find some time, but you can already fix those issues. Thank you again !

Do the indentation and line breaks matter? I thought this was set by \n and \t. Sorry abouth that :-( .

2023-10-07 10:26 UTC, Nain57 requested changes
Sorry, i had a rough week and didn't have the time to check your PR.

* I was talking about the indentation of the <strings> elements, always start them after 4 spaces. Inside the element, indentation doesn't matter, you are right.

* It still doesn't compile, the tutorial strings file seems incomplete.

* You have removed all the unecessary files, but you have also removed event_default_config.xml which contains the default names with events, conditions and actions, you might want to keep it https://github.com/Nain57/Smart-AutoClicker/pull/321/commits/44da88d9fd5611b7db63de413eb5f5c83baeb3eb#diff-03800a52bebcbb58e5347dc5798b8a8c14cc2dbcbfd527a49a5de1fd84bacfd9

2026-06-25 09:56 UTC, closed without merging