Added Arabic
Nain57/Smart-AutoClicker pull request #411
Opened 2024-04-22 16:42 UTC by muhammadbahaa2001

2024-04-30 15:41 UTC, Nain57 requested changes
Only the app module is translated, all other modules are missings

2024-08-17 00:13 UTC, muhammadbahaa2001 commented
I made some changes

2024-09-07 11:05 UTC, Nain57 commented
Hi and thank you again for your contribution.
Unfortunately, translation is not complete, as there is still some missing files. If you need an example, you can check this PR that have added the Portugues language: https://github.com/Nain57/Smart-AutoClicker/pull/438/files

Note: Sorry for the review delay, GitHub stills not send me a email/notification when receiving one (despite alerts being enabled in my settings -_-')

2024-09-07 11:31 UTC, muhammadbahaa2001 commented
> Hi and thank you again for your contribution.
> Unfortunately, translation is not complete, as there is still some missing files. If you need an example, you can check this PR that have added the Portugues language: https://github.com/Nain57/Smart-AutoClicker/pull/438/files
> 
> Note: Sorry for the review delay, GitHub stills not send me a email/notification when receiving one (despite alerts being enabled in my settings -_-')

I will add them.

2026-05-29 09:53 UTC, closed without merging